# Production overlay for Kong Gateway configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true
    
    services:
    - name: data-ingestion-service
      url: http://data-ingestion-service.default.svc.cluster.local:8080
      
    - name: data-processing-service
      url: http://data-processing-service.default.svc.cluster.local:8080
      
    - name: data-acquisition-service
      url: http://data-acquisition-service.default.svc.cluster.local:8080
    - name: user-service
      url: http://user-service.default.svc.cluster.local:8080
      
    
    routes:
    - name: ingestion-health
      service: data-ingestion-service
      paths:
      - /api/ingestion/health
      strip_path: false
      
    - name: ingestion-metrics
      service: data-ingestion-service
      paths:
      - /api/ingestion/internal/metrics/realtime
      strip_path: false
      
    - name: processing-health
      service: data-processing-service
      paths:
      - /api/processing/health
      strip_path: false
      
    - name: acquisition-health
      service: data-acquisition-service
      paths:
      - /api/acquisition/health
      strip_path: false
      
    - name: acquisition-entities
      service: data-acquisition-service
      paths:
      - /api/acquisition/entities
      strip_path: false
      
    - name: acquisition-fire-events
      service: data-acquisition-service
      paths:
      - /api/acquisition/fire-events
      strip_path: false
      
    - name: acquisition-aggregate
      service: data-acquisition-service
      paths:
      - /api/acquisition/aggregate
      strip_path: false
      
    - name: acquisition-monthly
      service: data-acquisition-service
      paths:
      - /api/acquisition/monthly
      strip_path: false
      
    - name: acquisition-realtime-logs
      service: data-acquisition-service
      paths:
      - /api/acquisition/realtime/logs
      strip_path: false

    - name: login
      service: user-service
      paths:
      - /api/auth/login
      strip_path: false

    
    
    plugins:
    - name: cors
      config:
        origins:
        - "https://your-frontend-domain.com"
        methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
        exposed_headers:
        - X-Auth-Token
        credentials: true
        max_age: 3600
        
    - name: rate-limiting
      config:
        minute: 10000
        hour: 100000
        policy: local
        
    - name: prometheus
      config:
        per_consumer: true
---
apiVersion: v1
kind: Service
metadata:
  name: kong-gateway
spec:
  type: LoadBalancer
  ports:
  - name: proxy
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: proxy-ssl
    port: 443
    targetPort: 8443
    protocol: TCP
  - name: admin-api
    port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: kong-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-gateway
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: kong
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: KONG_LOG_LEVEL
          value: "notice"
        - name: KONG_PLUGINS
          value: "bundled,cors,rate-limiting,prometheus"
        - name: KONG_NGINX_WORKER_PROCESSES
          value: "2"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        livenessProbe:
          httpGet:
            path: /status
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kong-gateway-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: kong-gateway