# Local overlay for Kong Gateway configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true
    
    services:
    - name: data-ingestion-service
      url: http://data-ingestion-service:8080
      routes:
      - name: ingestion-health
        paths:
        - /api/ingestion/health
        strip_path: false
      - name: ingestion-metrics
        paths:
        - /api/ingestion/internal/metrics/realtime
        strip_path: false
    
    - name: data-processing-service
      url: http://data-processing-service:8080
      routes:
      - name: processing-health
        paths:
        - /api/processing/health
        strip_path: false
    
    - name: data-acquisition-service
      url: http://data-acquisition-service:8080
      routes:
      - name: acquisition-health
        paths:
        - /api/acquisition/health
        strip_path: false
      - name: acquisition-entity-states
        paths:
        - /api/acquisition/entity-states
        strip_path: false
      - name: acquisition-fire-events
        paths:
        - /api/acquisition/fire-events
        strip_path: false
      - name: acquisition-collision-events
        paths:
        - /api/acquisition/collision-events
        strip_path: false
      - name: acquisition-detonation-events
        paths:
        - /api/acquisition/detonation-events
        strip_path: false
      - name: acquisition-aggregate
        paths:
        - /api/acquisition/aggregate
        strip_path: false
      - name: acquisition-monthly
        paths:
        - /api/acquisition/monthly
        strip_path: false
      - name: acquisition-realtime
        paths:
        - /api/acquisition/realtime
        strip_path: false
      - name: acquisition-metrics
        paths:
        - /api/acquisition/metrics
        strip_path: false
      - name: acquisition-realtime-logs
        paths:
        - /api/acquisition/realtime/logs
        strip_path: false
    - name: user-service
      url: http://user-service:8080
      routes:
      - name: login
        paths:
        - /api/auth/login
        strip_path: false

    plugins:
    - name: cors
      config:
        origins:
        - "*"
        methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        exposed_headers:
        - X-Auth-Token
        credentials: true
        max_age: 3600
    
    - name: rate-limiting
      config:
        minute: 1000
        hour: 10000
        policy: local
---
apiVersion: v1
kind: Service
metadata:
  name: kong-gateway-service
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 32080
    name: proxy
  - port: 8001
    targetPort: 8001
    nodePort: 32081
    name: admin
  - port: 8002
    targetPort: 8002
    nodePort: 32082
    name: manager