apiVersion: apps/v1
kind: Deployment
metadata:
  name: cap-pdu-prediction-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 5  # Retain 5 revisions for rollback
  selector:
    matchLabels:
      app: cap-pdu-prediction-service
  template:
    metadata:
      labels:
        app: cap-pdu-prediction-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: cap-pdu-prediction-service
        image: ghcr.io/nus-iss-projects/cap-pdu-prediction/cap-pdu-prediction:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        resources:
          limits:
            cpu: "2000m"
            memory: "4Gi"
            # Uncomment for GPU support
            # nvidia.com/gpu: 1
          requests:
            cpu: "500m"
            memory: "2Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        env:
          - name: FLASK_ENV
            value: "production"
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: DATA_ACQUISITION_URL
            value: "http://data-acquisition-service:8080"
          - name: DATA_INGESTION_URL
            value: "http://data-ingestion-service:8080"
          - name: DATA_PROCESSING_URL
            value: "http://data-processing-service:8080"
          - name: USE_GPU
            value: "false"
          - name: MODEL_NAME
            value: "microsoft/DialoGPT-small"
          - name: TRANSFORMERS_CACHE
            value: "/tmp/transformers_cache"
          - name: HF_HOME
            value: "/tmp/huggingface_cache"
          - name: USE_CACHING
            value: "true"
          - name: CACHE_TTL_SECONDS
            value: "300"
          - name: MAX_RESPONSE_TIME
            value: "3.0"