apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processing-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 5  # Retain 5 revisions for rollback
  selector:
    matchLabels:
      app: data-processing-service
  template:
    metadata:
      labels:
        app: data-processing-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: data-processing-service
        image: ghcr.io/nus-iss-projects/cap-backend-data-processing/cap-backend-data-processing:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "768Mi"
          requests:
            cpu: "100m"
            memory: "384Mi"
        readinessProbe:
          httpGet:
            path: /api/processing/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/processing/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        env:
          - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
            value: "kafka:9092"
          - name: KAFKA_TOPIC
            value: "dis-pdus"
          - name: SPRING_KAFKA_CONSUMER_GROUP_ID
            value: "processing-group"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://postgres:5432/dis_db"
          - name: SPRING_DATASOURCE_USERNAME
            value: "dis_user"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "dis_pass"

