apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 5  # Retain 5 revisions for rollback
  selector:
    matchLabels:
      app: data-ingestion-service
  template:
    metadata:
      labels:
        app: data-ingestion-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: data-ingestion-service
        image: ghcr.io/nus-iss-projects/cap-backend-data-ingestion/cap-backend-data-ingestion:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080  # Spring Boot HTTP port
        - containerPort: 3000  # UDP listener port
          protocol: UDP
        resources:
          limits:
            cpu: "200m"
            memory: "512Mi"
          requests:
            cpu: "50m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /api/ingestion/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /api/ingestion/health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        env:
          - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
            value: "kafka:9092"
          - name: KAFKA_TOPIC
            value: "dis-pdus"
          - name: UDP_PORT
            value: "3000"
          - name: UDP_BUFFER_SIZE
            value: "2048"

