apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: data-ingestion-hpa
  namespace: default # Or your target namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data-ingestion-service # Matches the name of your Data Ingestion Service Deployment
  minReplicas: 1
  maxReplicas: 2 # Adjust as needed
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        # Target 70% of the requested CPU.
        # If request is 50m, HPA will scale up if average usage > 35m.
        averageUtilization: 70