resources:
  - data-ingestion-service-deployment.yaml
  - data-ingestion-service.yaml
  - data-ingestion-service-udp.yaml
  - data-processing-service-deployment.yaml
  - data-processing-service.yaml
  - kafka-service.yaml
  - kafka-statefulset.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - zookeeper-service.yaml
  - zookeeper-statefulset.yaml

secretGenerator:
  # GHCR Docker Registry secret
  - name: ghcr-secret
    files:
      - .dockerconfigjson  # File generated dynamically in the GitHub Actions workflow
    type: kubernetes.io/dockerconfigjson

generatorOptions:
  disableNameSuffixHash: true

# resources:
#   - ingress.yaml
#   - storage-class.yaml
#   - kafka-statefulset.yaml
#   - kafka-service.yaml
#   - zookeeper-statefulset.yaml
#   - zookeeper-service.yaml
#   - watchlist-deployment.yaml
#   - watchlist-service.yaml
#   - watchlist-hpa.yaml
#   - notification-deployment.yaml
#   - notification-service.yaml
#   - notification-hpa.yaml
#   - user-deployment.yaml
#   - user-service.yaml
#   - user-hpa.yaml
#   - coin-deployment.yaml
#   - coin-service.yaml
#   - coin-hpa.yaml
#   - redis-statefulset.yaml
#   - redis-service.yaml
  
# secretGenerator:
#   # GHCR Docker Registry secret
#   - name: ghcr-secret
#     files:
#       - .dockerconfigjson  # File generated dynamically in the GitHub Actions workflow
#     type: kubernetes.io/dockerconfigjson

#   # Firebase config for notification-service
#   - name: firebase-config-notification
#     files:
#       - google-services-notification.json

#   # Firebase config for user-service
#   - name: firebase-config-user
#     files:
#       - google-services-user.json

#   # Firebase config for watchlist-service
#   - name: firebase-config-watchlist
#     files:
#       - google-services-watchlist.json

# generatorOptions:
#   disableNameSuffixHash: true