apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: postgres-backup
            image: postgres:14
            command:
            - /bin/bash
            - -c
            - |
              BACKUP_FILE="/backup/postgres-backup-$(date +%Y%m%d-%H%M%S).sql"
              echo "Starting backup to $BACKUP_FILE"
              pg_dump -h postgres -U dis_user -d dis_db > "$BACKUP_FILE"
              if [ $? -eq 0 ]; then
                echo "Backup completed successfully: $BACKUP_FILE"
                # Keep only the last 7 backups
                find /backup -name "postgres-backup-*.sql" -type f -mtime +7 -delete
                echo "Old backups cleaned up"
              else
                echo "Backup failed"
                exit 1
              fi
            env:
            - name: PGPASSWORD
              value: "dis_pass"
            volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: postgres-storage
              mountPath: /backup
              subPath: backups
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
          volumes:
          - name: postgres-storage
            persistentVolumeClaim:
              claimName: postgres-storage-postgres-0