# Staging overlay for Kong Gateway configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true
    
    services:
    - name: data-ingestion-service
      url: http://data-ingestion-service.default.svc.cluster.local:8080
      
    - name: data-processing-service
      url: http://data-processing-service.default.svc.cluster.local:8080
      
    - name: data-acquisition-service
      url: http://data-acquisition-service.default.svc.cluster.local:8080
    
    routes:
    - name: ingestion-health
      service: data-ingestion-service
      paths:
      - /api/ingestion/health
      strip_path: false
      
    - name: ingestion-metrics
      service: data-ingestion-service
      paths:
      - /api/ingestion/internal/metrics/realtime
      strip_path: false
      
    - name: processing-health
      service: data-processing-service
      paths:
      - /api/processing/health
      strip_path: false
      
    - name: acquisition-health
      service: data-acquisition-service
      paths:
      - /api/acquisition/health
      strip_path: false
      
    - name: acquisition-entities
      service: data-acquisition-service
      paths:
      - /api/acquisition/entities
      strip_path: false
      
    - name: acquisition-fire-events
      service: data-acquisition-service
      paths:
      - /api/acquisition/fire-events
      strip_path: false
      
    - name: acquisition-aggregate
      service: data-acquisition-service
      paths:
      - /api/acquisition/aggregate
      strip_path: false
      
    - name: acquisition-monthly
      service: data-acquisition-service
      paths:
      - /api/acquisition/monthly
      strip_path: false
      
    - name: acquisition-realtime-logs
      service: data-acquisition-service
      paths:
      - /api/acquisition/realtime/logs
      strip_path: false
    
    plugins:
    - name: cors
      config:
        origins:
        - "*"
        methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        exposed_headers:
        - X-Auth-Token
        credentials: true
        max_age: 3600
        
    - name: rate-limiting
      config:
        minute: 5000
        hour: 50000
        policy: local
---
apiVersion: v1
kind: Service
metadata:
  name: kong-gateway
spec:
  type: LoadBalancer
  ports:
  - name: proxy
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: admin-api
    port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: kong-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kong-gateway
  template:
    spec:
      containers:
      - name: kong
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: KONG_LOG_LEVEL
          value: "info"
        - name: KONG_PLUGINS
          value: "bundled,cors,rate-limiting"