# Staging overlay for Kong Gateway configuration with Firebase JWT
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config-firebase
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true
    
    services:
    # Data Ingestion Service
    - name: data-ingestion-service
      url: http://data-ingestion-service.default.svc.cluster.local:8080
      routes:
      # Health endpoint - NO authentication
      - name: data-ingestion-health
        paths:
        - /api/ingestion/health
        strip_path: false
      # All other ingestion endpoints - WITH authentication
      - name: data-ingestion-protected
        paths:
        - /api/ingestion
        strip_path: false
        plugins:
        - name: jwt-firebase
          config:
            firebase_project_id: "cap-backend-user"
        
    # Data Processing Service
    - name: data-processing-service
      url: http://data-processing-service.default.svc.cluster.local:8080
      routes:
      # Health endpoint - NO authentication
      - name: data-processing-health
        paths:
        - /api/processing/health
        strip_path: false
      # All other processing endpoints - WITH authentication
      - name: data-processing-protected
        paths:
        - /api/processing
        strip_path: false
        plugins:
        - name: jwt-firebase
          config:
            firebase_project_id: "cap-backend-user"

        
    # PDU Prediction Service
    - name: cap-pdu-prediction-service
      url: http://cap-pdu-prediction-service.default.svc.cluster.local:5001
      routes:
      # Health endpoint - NO authentication
      - name: prediction-health
        paths:
        - /api/prediction/health
        strip_path: false
      # Chat status endpoint - NO authentication (for monitoring)
      - name: prediction-chat-status
        paths:
        - /api/prediction/chat/status
        strip_path: false
      # Chat endpoint - WITH authentication
      - name: prediction-chat
        paths:
        - /api/prediction/chat
        strip_path: false
        plugins:
        - name: jwt-firebase
          config:
            firebase_project_id: "cap-backend-user"
      # Prediction endpoints - WITH authentication
      - name: prediction-protected
        paths:
        - /api/prediction
        strip_path: false
        plugins:
        - name: jwt-firebase
          config:
            firebase_project_id: "cap-backend-user"
        
    # Data Acquisition Service
    - name: data-acquisition-service
      url: http://data-acquisition-service.default.svc.cluster.local:8080
      routes:
      # Health endpoint - NO authentication
      - name: data-acquisition-health
        paths:
        - /api/acquisition/health
        strip_path: false
      # All other acquisition endpoints - WITH authentication
      - name: data-acquisition-protected
        paths:
        - /api/acquisition
        strip_path: false
        plugins:
        - name: jwt-firebase
          config:
            firebase_project_id: "cap-backend-user"
        
    # User Service
    - name: cap-user-service
      url: http://cap-user-service.default.svc.cluster.local:8080
      routes:
      # Health endpoint - NO authentication
      - name: user-health
        paths:
        - /api/user/health
        strip_path: false
      # Public auth endpoints - NO authentication
      - name: user-auth-public
        paths:
        - /api/auth/login
        - /api/auth/register
        strip_path: false
      # Protected user endpoints - WITH authentication
      - name: user-protected
        paths:
        - /api/users
        - /api/user-sessions
        strip_path: false
        plugins:
        - name: jwt-firebase
          config:
            firebase_project_id: "cap-backend-user"
    
    plugins:
    - name: cors
      config:
        origins:
        - "*"
        methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        exposed_headers:
        - X-Auth-Token
        credentials: true
        max_age: 3600
        
    - name: rate-limiting
      config:
        minute: 5000
        hour: 50000
        policy: local
---
apiVersion: v1
kind: Service
metadata:
  name: kong-gateway-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: admin-api
    port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: kong-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-gateway
  template:
    spec:
      containers:
      - name: kong
        resources:
          requests:
            memory: "384Mi"
            cpu: "100m"
          limits:
            memory: "768Mi"
            cpu: "300m"
        env:
        - name: KONG_LOG_LEVEL
          value: "info"
        - name: KONG_PLUGINS
          value: "bundled,cors,rate-limiting,jwt-firebase"
        readinessProbe:
          httpGet:
            path: /status
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /status
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 30